Repository googleapis/java-conformance-tests, pull requests merged in 2020-09, with the labels that each got.

#181 chore: add repo settings config
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
Labels: cla: yes

#182 chore: exlcude auto-release from running in this repo
  synth.py
Labels: cla: yes

#184 chore: release v0.0.12
  CHANGELOG.md
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#192 chore: add codeowner_team value to .repo-metadata.json
  .repo-metadata.json
Labels: automerge, cla: yes

#200 chore: regenerate CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: partial

#193 build: add .github/workflows/generate.yaml action
  .github/workflows/generate.yaml
  generate-conformance-tests.sh
Labels: api: cloudbuild, cla: yes

#207 Revert "build(deps): update dependency com.coveo:fmt-maven-plugin to v2.10"
  pom.xml
Labels: automerge, cla: yes

#210 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
