Repository googleapis/java-conformance-tests, pull requests merged in 2020-08, with the labels that each got.

#165 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: cla: yes, context: full

#166 chore: remove accidentally added pyenv file
  .python-version
Labels: cla: yes

#167 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#170 chore(build): update synth ignore to include .github/workflows/samples.yaml
  synth.py
Labels: cla: yes

#172 samples: update presubmit lint check config
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: full

#176 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#178 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
