Repository googleapis/java-conformance-tests, pull requests merged in 2020-06, with the labels that each got.

#139 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#140 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#143 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#149 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  pom.xml
Labels: cla: yes

#151 build: fix maven config errors preventing code generation
  pom.xml
Labels: cla: yes
