Repository googleapis/java-conformance-tests, pull requests merged in 2020-05, with the labels that each got.

#125 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#126 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#136 deps: update dependency com.google.guava:guava-bom to v29
  pom.xml
Labels: automerge, cla: yes
