Repository googleapis/java-conformance-tests, pull requests merged in 2021-09, with the labels that each got.

#360 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, automerge, context: full

#362 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#365 chore: Update CODEOWNERS for @googleapis/cloud-storage-dpe
  .github/CODEOWNERS
  .repo-metadata.json
Labels: cla: yes

#366 chore: remove readme autosynth config
  .kokoro/continuous/readme.cfg
Labels: cla: yes

#368 chore: re-generated to pick up changes from synthtool.
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: partial

#379 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes

#383 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#385 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, automerge
