Repository googleapis/java-conformance-tests, pull requests merged in 2021-02, with the labels that each got.

#264 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: partial

#265 Revert "chore: Re-generated to pick up changes from self."
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes

#266 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#268 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#271 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#272 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#273 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#275 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
